version: '2'
services:
  monitor:
    image: monitor
    expose:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker:ro
      - /config.yml:/app/config.yml
